### ISSUE TITLE
can''t open display

### ISSUE THREAD

**Issue by japrogramer** [flathub/org.libreoffice.LibreOffice#186]
I updated the flatpak and now I cant open it

```
▶ flatpak run org.libreoffice.LibreOffice                                                           ∞
Failed to open display
▶ flatpak run --command=sh org.libreoffice.LibreOffice                                              ∞
[📦 org.libreoffice.LibreOffice Archives]$ echo $GDK_BACKEND:$WAYLAND_DISPLAY:$DISPLAY
:wayland-1:

```

**Comment by japrogramer** [comment]
This flatpak used to work fine

**Comment by japrogramer** [comment]
even tho im running wayland I had to do this to get it working
```
▶ flatpak --socket=x11 --command=sh run org.libreoffice.LibreOffice                                                                                                                                             ∞
[📦 org.libreoffice.LibreOffice Archives]$ echo $GDK_BACKEND:$WAYLAND_DISPLAY:$DISPLAY
:wayland-1:
[📦 org.libreoffice.LibreOffice Archives]$ export DISPLAY=:0
[📦 org.libreoffice.LibreOffice Archives]$ libreoffice

```

**Comment by stbergmann** [comment]
This appears to be a consequence of merging <https://github.com/flathub/org.libreoffice.LibreOffice/pull/183> "Change socket to fallback-x11 to fix 'Unsafe' warning" as <https://github.com/flathub/org.libreoffice.LibreOffice/commit/73544403cde6d08ead0d6a15ba6505e457272583> "Change socket to fallback-x11" (which I had pulled somewhat blindly, not knowing much about the exact details of those --socket=[fallback-]x11 flags).

@japrogramer Just in case, what version of flatpak are you running, on what distro?

@ourigen Any idea whether that PR could be problematic after all?

**Comment by japrogramer** [comment]
```
▶ pacman -Qii flatpak                                                                                                                                                                                           ∞
Name            : flatpak
Version         : 1:1.12.7-1
Description     : Linux application sandboxing and distribution framework (formerly xdg-app)
Architecture    : x86_64
URL             : https://flatpak.org
Licenses        : LGPL
Groups          : None
Provides        : libflatpak.so=0-64
Depends On      : dbus  glib2  libsoup  polkit  libxau  ostree  json-glib  libseccomp  libarchive  python  bubblewrap  appstream-glib  xdg-dbus-proxy  systemd  xdg-desktop-portal
Optional Deps   : None
Required By     : flatpak-builder
Optional For    : None
Conflicts With  : None
Replaces        : None
Installed Size  : 7.54 MiB
Packager        : Jan Alexander Steffens (heftig) <heftig@archlinux.org>
Build Date      : Mon 14 Mar 2022 03:57:19 PM CDT
Install Date    : Wed 16 Mar 2022 09:47:28 PM CDT
Install Reason  : Explicitly installed
Install Script  : No
Validated By    : Signature
Backup Files    :
(none)
▶ uname -r; pacman -Q linux                                                                                                                                                                                     ∞
5.17.4-arch1-1
linux 5.17.5.arch1-1


### 



LibreOffice                                         org.libreoffice.LibreOffice                     7.3.2.2              stable

```


When I use fallback-x11 it works but I still have to set the env var inside the container

```
▶ flatpak --socket=fallback-x11 --command=sh run org.libreoffice.LibreOffice                                                                                                                                    ∞
[📦 org.libreoffice.LibreOffice Archives]$ libreoffice
Failed to open display
^C
(reverse-i-search)`': ^C
[📦 org.libreoffice.LibreOffice Archives]$ export DISPLAY=:0
[📦 org.libreoffice.LibreOffice Archives]$ libreoffice
```

**Comment by Erick555** [comment]
Assuming LO supports native wayland display then it looks like flatpak can't detect wayland socket on this system but it isn't LO fault.

Does any other flatpak app with `--socket=fallback-x11` `--socket=wayland` work?

**Comment by japrogramer** [comment]
Do you know of one I could test?

**Comment by Erick555** [comment]
Maybe try `com.github.tchx84.Flatseal` for example. The wayland-1 socket name is suspicious. What `echo $WAYLAND_DISPLAY` prints on your host?

**Comment by Erick555** [comment]
Also `ls -al /run/user/*/wayland*`

**Comment by ourigen** [comment]
Chiming in to say that `--socket=fallback-x11` was tested to be working when I made the PR and is currently working for me, at least on GNOME 42.

[Docs](https://docs.flatpak.org/en/latest/flatpak-command-reference.html) says that `fallback-x11` option makes the X11 socket available only if there is no Wayland socket. As far as I know LO supports Wayland, so it should've default to `--socket=wayland` and have no trouble with X11 ideally. We *could* add both `--socket=x11` and `--socket=fallback-x11` for compatibility. The latter will take precedent.

@japrogramer It seems that your `$DISPLAY` isn't being set by sway. Do you have

```
export XDG_SESSION_TYPE=wayland
export XDG_CURRENT_DESKTOP=sway
```
in your config? If not, could you try with those variables?

**Comment by japrogramer** [comment]
@Erick555 @ourigen 

Here are the results of running those commands

```
▶ export XDG_SESSION_TYPE=wayland                                                                                                                                                                               ∞
export XDG_CURRENT_DESKTOP=sway

~
▶ env | ack XDG                                                                                                                                                                                                 ∞
XDG_DATA_DIRS=/home/archangel/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share/:/usr/share/
XDG_RUNTIME_DIR=/run/user/1000
XDG_SEAT=seat0
XDG_SESSION_CLASS=user
XDG_SESSION_ID=1
XDG_SESSION_TYPE=wayland
XDG_VTNR=1
XDG_CURRENT_DESKTOP=sway

~
▶ echo $WAYLAND_DISPLAY                                                                                                                                                                                         ∞
wayland-1

~
▶ ls -al /run/user/*/wayland*                                                                                                                                                                                   ∞
srwxr-xr-x 1 archangel archangel 0 May  2 16:57 /run/user/1000/wayland-1
-rw-r----- 1 archangel archangel 0 May  2 16:57 /run/user/1000/wayland-1.lock

~
▶ flatpak run org.libreoffice.LibreOffice                                                                                                                                                                       ∞
Failed to open display
^C
```

**Comment by Erick555** [comment]
Did you try with any other flatpak? If it's reproducible elsewhere then [this](https://github.com/flatpak/flatpak/issues) may be better place to address the issue

**Comment by japrogramer** [comment]
I rebooted and it started working again, no other settings changed.

**Comment by JamesBelchamber** [comment]
This is also happening to me on Fedora Silverblue 36. I note that [the Fedora LibreOffice Flatpak](https://src.fedoraproject.org/flatpaks/libreoffice/blob/stable/f/container.yaml) sticks to `--socket=x11`.

Does it make sense to revert #183 until a fix is found here? Or is it just two of us having this issue :sweat_smile:

**Comment by nelas** [comment]
For me as well on Ubuntu 22.04.1 LTS, GNOME 42.4, Wayland. It only started happening recently, several months after the March commit #183. After reboot, it shows the same `Failed to open display` message, but it works, temporarily. Other flatpaks open fine. Here are the outputs for the commands mentioned above:

```
$ flatpak run org.libreoffice.LibreOffice 
Failed to open display
^C
$ flatpak --version
Flatpak 1.12.7
$ uname -r
5.15.0-47-generic
$ flatpak --socket=fallback-x11 run org.libreoffice.LibreOffice 
Failed to open display
^C
$ echo $WAYLAND_DISPLAY
wayland-0
$ ls -al /run/user/*/wayland*
srwxrwxr-x 1 nelas nelas 0 Sep 12 22:26 /run/user/1000/wayland-0
-rw-rw---- 1 nelas nelas 0 Sep 12 22:26 /run/user/1000/wayland-0.lock
$ echo $XDG_SESSION_TYPE
wayland
$ echo $XDG_CURRENT_DESKTOP
GNOME
$ flatpak run org.libreoffice.LibreOffice 
Failed to open display
^C
```

**Comment by ourigen** [comment]
Hi everyone, sorry I have been MIA. It seems that the PR is causing trouble for enough of you. We may try to add both `--socket=x11` and `--socket=fallback-x11`. From what I understand, the latter will take precedent and the former preserves compatibility for older Flatpaks. Could one of you test if running the Flatpak with `--socket=x11 --socket=fallback-x11 --socket=wayland` fixes the issue?

**Comment by Erick555** [comment]
This isn't old flatpak issue. Version reported here are relatively new.

**Comment by bruvellu** [comment]
Hey, I found a fix, but not the cause.

Every time you open a document, LO starts the four processes below. And when you close the document, the processes are shut down.

![image](https://user-images.githubusercontent.com/361179/201543772-41e4e547-b465-4c5c-9ea5-5e698b0a8a3c.png)

But I noticed that every time LO failed to open a document, these four processes were already running, even though no documents were open. My guess is that they weren't shut down when a previously opened document was closed. The solution was simple: killing this zombie `soffice.bin` process (and consequently the others) allowed opening documents again.

I was able to reproduce the issue by opening several documents at the same time and then closing them. At some point, there would be one `soffice.bin` left over and that would prevent me from opening further documents. This explains the strange behavior that rebooting would help but only temporarily, until the issue started occurring again.

All of this was happening with the versions reported [above](https://github.com/flathub/org.libreoffice.LibreOffice/issues/186#issuecomment-1245921636), but now I've upgraded my system and with `LibreOffice 7.4.2.3`, `Flatpak 1.14.0`, `GNOME 43.0` and `Ubuntu 22.10`, the issue is no longer happening to me.

So it's perhaps not related to the `Failed to open display` message (it still appears to me...) but to something about the launching/closing of the application which is fixed in these newer versions. If you experience the issue, check the system monitor and kill any hanging `soffice.bin` and see if this works.

Hope this helps

**Comment by stbergmann** [comment]
> I was able to reproduce the issue by opening several documents at the same time and then closing them. At some point, there would be one `soffice.bin` left over and that would prevent me from opening further documents. This explains the strange behavior that rebooting would help but only temporarily, until the issue started occurring again.

(1) I can reproduce with the latest LO 7.4.2.3 flatpak on Fedora 37/GNOME 43.1/Wayland, that a `Failed to open display` is indeed always printed to stderr on start of LO.  But that is apparently harmless, as (for me), LO then proceeds to start fine and displays a window.

(2) LO makes sure that at most one `soffice.bin` process is running at any point in time.  For that, the running `soffice.bin` listens on a connection (a named pipe for plain non-flatpak'ed LO, a dbus connection for the flatpak'ed LO), and when you start LO its initial `oosplash` process first tries to connect to an existing `soffice.bin`.  If that succeeds, it hands over to the existing instance via the established connection, otherwise it starts the first and only `soffice.bin`.

If an `soffice.bin` is still running, it likely still listens on the connection.  So the issue you describe can either be that that `soffice.bin` is still operational and when a second LO is started to open a document the first one opens it but doesn't get to the foreground so you don't notice and think the second LO invocation failed (which is probably unlikely to be the case here).  Or the still-running `soffice.bin` is no longer properly operational (but still listens on the connection), in which case it would be interesting to see backtraces of all the threads of the still-running `soffice.bin` process.

**Comment by nekohayo** [comment]
while running on Fedora 42's Wayland GNOME 48 session on open source AMD graphics drivers from Mesa, this issue and #249 seemed to have resurfaced with the latest update version from today, i.e. commit 57bedab29b66f56f31e7e1304f88db6c57bad08dcf363b9d763db87c2d80b26a from MR #328. It occurred even if I had made sure that no lingering soffice.bin process was running (using gnome-system-monitor).

Nothing worked until I asked flatpak to revert to commit 0220871080 (2025-04-30 14:22:40 +0000, `Merge pull request #323 from flathub/lo-25.2.3 (2a94cf00c88d)`), it worked fine with that previous version.

But then, what's even weirder is that when I upgraded back to the latest commit (i.e. 57bedab2), there it worked again. Yet I hadn't done anything special, I hadn't logged out or anything like that...
