### ISSUE TITLE
OpenJDK 10 is now available

### ISSUE THREAD

**Issue by nedrichards** [flathub/org.libreoffice.LibreOffice#42]
I'm not sure if this is particularly useful but OpenJDK10 is now available on Flathub. The main advantage for appears to be that SSL now works properly if you do network transfer. Not sure if that is possible or likely in LO, but if it it it'd possibly be worth updating.

**Comment by stbergmann** [comment]
blocking on <https://github.com/flathub/org.freedesktop.Sdk.Extension.openjdk10/issues/2> "Path to JDK /usr/lib/sdk/openjdk10/jvm/openjdk-10.0.1 contains minor/micro (which may change?)"

**Comment by stbergmann** [comment]
So both flathub builds so far of <https://github.com/flathub/org.libreoffice.LibreOffice/commit/e45d16b4c607c98e7ef2a9a173b296ea900c2e29> "Merge pull request #44 from flathub/openjdk10" failed on aarch64 with a SEGV during CppunitTest_dbaccess_RowSetClones (<https://flathub.org/builds/#/builders/40/builds/198> and <https://flathub.org/builds/#/builders/37/builds/208>).  While that test is known to occasionally (though rarely) fail across various platforms (though with some test assertion failure output, not a SEGV), it is also utilizing Java.  So I'll take that as strong indication that something is wrong with org.freedesktop.Sdk.Extensions.openjdk10 and aarch64, which will need further investigation.

**Comment by stbergmann** [comment]
The CppunitTest_dbaccess_RowSetClones issue mentioned above is discussed in the mail thread around <http://mail.openjdk.java.net/pipermail/aarch64-port-dev/2018-June/006070.html> "[aarch64-port-dev ] Sporadic crashes on aarch64 after switching from OpenJDK 9 to 10" and fixed with <https://github.com/flathub/org.libreoffice.LibreOffice/commit/4fdd8085f0a777049589571bc6f42c291be54260> "Fix sporadic Java-related test failures".
<https://flathub.org/builds/#/builders/2/builds/2372> contains OpenJDK 10 now.

**Comment by mbooth101** [comment]
Nice work! Glad you got it working :-)
