### ISSUE TITLE
Add JRE-based components

### ISSUE THREAD

**Issue by eszlari** [flathub/org.libreoffice.LibreOffice#5]
https://bugs.documentfoundation.org/show_bug.cgi?id=114474

On the flatpak download page (http://www.libreoffice.org/download/flatpak) one can read the following:

"The LibreOffice Flatpak does not include a Java Runtime Environment (JRE). That means that some LibreOffice functionality that requires a JRE will not work."

Too bad it doesn't explain why. Flathub contains other apps, that either use "org.freedesktop.Sdk.Extension.openjdk9":

https://github.com/flathub/com.jetbrains.PyCharm-Community

Or bundle JRE:

https://github.com/flathub/org.geogebra.GeoGebra

**Comment by stbergmann** [comment]
Originally, the main motivation to not include a JRE in the LO flatpak was to not be forced into the business of tracking JRE (security) issues and rebuilding the LO flatpak with an updated JRE when necessary.  (All the other code in the LO flatpak that is not covered by the flatpak runtime/sdk is tracked by TDF, issuing new LO releases when necessary, so any relevant fixes automatically make their way into the LO flatpak releases.)

The introduction of org.freedesktop.Sdk.Extension.openjdk9 a while ago will hopefully address that in a reasonable way, allowing maintainers of dependent flatpak apps to learn about updates to that openjdk9 extensions, so that they can produce updates of their apps accordingly.  (I'll follow up with Alex on this question.)

So make the LO flatpak use that openjdk9 extension, as done with the referenced commits for master (towards LO 6.1) and libreoffice-6-0.

LO 5.4 lacks some patches that would allow it to build against JDK 9, so I decided to not backport this fix into the current LO 5.4.4 flatpak, but instead wait for the next LO 6.0.0 flatpak, which is the next scheduled release on the LO "Fresh" stream (which the LO flatpak releases on flathub follow), due in a few weeks (see <https://wiki.documentfoundation.org/Release_Plan>).

(Note to self: remember to remove the item about missing JRE from <https://www.libreoffice.org/download/flatpak> once the LO 6.0 flatpak is available.)

**Comment by stbergmann** [comment]
fixed now with the LO 6.0.0 flatpak being available

(and I removed the item about missing JRE from <https://www.libreoffice.org/download/flatpak/>)
