### ISSUE TITLE
UTF-8 error

### ISSUE THREAD

**Issue by gyhun95** [flathub/org.libreoffice.LibreOffice#51]
Hy all! I've an annoying error, while I want to open my not english docs in a not eng dir.

![kepernyokep errol 2018-08-26 09-38-27](https://user-images.githubusercontent.com/42371586/44707425-c61dcb80-aaa4-11e8-96bb-aa015e75b694.png)

**Comment by stbergmann** [comment]
Hard to tell what's going wrong without further information.
* What's your locale?  In a terminal, type `locale` and show the output.
* What's the byte-for-byte names of that Let... directory and the 201808_... file in the directory?  In a terminal, type `LC_ALL=C ls -d --quoting-style=c /sysroot/home/gyhun95/Let* /sysroot/home/gyhun95/Let*/201808_*´ (assuming GNU ls) and show the output.
* How do you start LO and request that file to be opened, do you click on that file in some file manager, or do you start LO from a terminal?

**Comment by gyhun95** [comment]
Okay, so:
-output_
![kepernyokep errol 2018-09-03 08-36-17](https://user-images.githubusercontent.com/42371586/44971056-76337e80-af54-11e8-8c37-48f77530b649.png)
-Full name is(not august, but september now...): /sysroot/home/gyhun95/Letöltések/201809_Szeptember_Mentésirányítás.xlsx
![kepernyokep errol 2018-09-03 08-41-05](https://user-images.githubusercontent.com/42371586/44971245-21443800-af55-11e8-9981-ce7ba03444e3.png)
-I use both two methods click and open or open from libre, but get the same error...

Thanks for the answer!

**Comment by stbergmann** [comment]
That's odd.  So your pathnames are apparently valid UTF-8 (containing UTF-8 encodings of "Letöltések" and "Mentésirányítás"), and at least the locale in your terminal shell is hu_HU.UTF-8.

What happens, after making sure that LO is not running, when you start LO from the terminal shell, `flatpak run org.libreoffice.LibreOffice`, and then in LO use "File - Open..." to open the file?

And what happens, again after making sure that LO is not running, when you start LO and request it to open the file from the terminal shell, `flatpak run org.libreoffice.LibreOffice /sysroot/home/gyhun95/Letöltések/201809_Szeptember_Mentésirányítás.xlsx`?

**Comment by gyhun95** [comment]
1.:
![kepernyokep errol 2018-09-03 12-14-10](https://user-images.githubusercontent.com/42371586/44981470-e94bed80-af72-11e8-8b94-278ce0b16205.png)
2.: 
![kepernyokep errol 2018-09-03 12-15-56](https://user-images.githubusercontent.com/42371586/44981529-21ebc700-af73-11e8-98fe-a3e7a6ed7253.png)

**Comment by stbergmann** [comment]
The GTK warning about "Using the fallback 'C' locale' may be a hint. Did you install org.freedesktop.Platform.Locale to have support for your hu_HU.UTF-8 locale (similar to what you asked for org.libreoffice.LibreOffice.Locale in <https://github.com/flathub/org.libreoffice.LibreOffice/issues/50> "Langauge packs are missing")?

**Comment by gyhun95** [comment]
Finally, flatpak update helped... Thx for nothing again.

**Comment by DirtyJukebox** [comment]
Hello there, I'm afraid this issue has re-surfaced:
`
![image](https://user-images.githubusercontent.com/26551202/89544970-25300300-d7d9-11ea-86cd-9b1c57eb09ba.png)
`
If I move the file to` /home/khalil/Relatorio.odt` (no special/non-US chars) it works again. I'm pretty sure this bug was introduced somewhere in the 6.X series, but it's also present in the 7.X series of LibreOffice. Or I might be completely wrong and this is a portal/sandbox issue introduced by a flatpak update =p.

Running from the terminal shows this:
```
khalil:~ % flatpak run org.libreoffice.LibreOffice /home/khalil/Documentos/CS/Fase5/Arquitetura/Avaliações/M2-P2/Rel

(soffice:36): Gtk-WARNING **: 11:36:06.820: Locale not supported by C library.
        Using the fallback 'C' locale.
Gtk-Message: 11:36:06.820: Failed to load module "canberra-gtk-module"

```

The original filename was `/home/khalil/Documentos/CS/Fase5/Arquitetura/Avaliações/M2-P2/Relatório.odt` and my locale is `pt_BR.UTF-8`

**Comment by stbergmann** [comment]
Try `flatpak install --reinstall org.freedesktop.Platform.Locale`.  Smells like your Platform.Locale is only partial and lacks pt_BR.UTF-8 support.

**Comment by Erick555** [comment]
It's possible that flatpak can't detect you system locale properly: https://github.com/flatpak/flatpak/issues/3712

**Comment by DirtyJukebox** [comment]
@stbergmann thank you very much it worked! Now that I think about it kinda makes sense, I've recently reinstalled my OS, created new user, etc. And during the installation I forgot to set my locale before running my setup script (which installs my apps), so flatpak couldn't pickup my locale because it wasn't set then.

Thanks!
