### ISSUE TITLE
wrong icon on the dock

### ISSUE THREAD

**Issue by laichiaheng** [flathub/org.libreoffice.LibreOffice#60]
I opened Writer, but it popped out another icon.
![2018-11-18 21-49-46](https://user-images.githubusercontent.com/9532105/48673402-e331da00-eb7b-11e8-9b9c-6fdf10fae447.png)

**Comment by Ethunxxx** [comment]
I have the same problem. Any updates on this one?

**Comment by theworldisnotflat** [comment]
have also the problem
Ubuntu 18.04 flatpak LibreOffice 6.4.3.2

**Comment by stbergmann** [comment]
That is also how non-Flatpak versions of LibreOffice work, at least on a GNOME desktop:  While there are multiple org.libreoffice.LibreOffice*.desktop launcher files with different icons (for Writer, Calc, etc.), every LibreOffice document window uses the generic white document icon, and that is what shows up in desktops' iconic "open applications" lists.  (IIUC, the reason is that such a LibreOffice document window can be repurposed e.g. from being a Writer to being a Calc document, but it would no be easy to change the window's icon correspondingly, at least on GNOME, so it is simply set to the generic one in the first place.)

Thus closing as "wontfix".

**Comment by stbergmann** [comment]
(i.e., see <https://bugzilla.redhat.com/show_bug.cgi?id=1334915> "Libreoffice Missing icons on dock and Alt+tab on Wayland" and <https://git.libreoffice.org/core/+/6903066822900a700ccf67ae70fa171c94644a9a%5E!/> "Related: rhbz#1334915 tdf#100158 hack using startcenter icon under wayland")

**Comment by theworldisnotflat** [comment]
> That is also how non-Flatpak versions of LibreOffice work, at least on a GNOME desktop

I have the right icons in the dock with the regular LibreOffice deb package install from the ubuntu repository; I only have the problem with Flatpak and Snap versions of LibreOffice

**Comment by stbergmann** [comment]
> > That is also how non-Flatpak versions of LibreOffice work, at least on a GNOME desktop

More precisely, I should have written "at least on a GNOME desktop when running on Wayland".  On X11, or with a non gtk or gtk3 VCL backend (see "Help - About LibreOffice" for the VCL backend used), the icons of the individual LibreOffice document windows should match the document categories instead of always using the generic icon.

> I have the right icons in the NOME dock with the regular LibreOffice deb package install from the ubuntu repository; I only have the problem with Flatpak and Snap versions of LibreOffice

If I try with a fresh Ubuntu 18.04.4 install:
* The session apparently does not run on Wayland (`set | grep WAYLAND` in a terminal turns up nothing).
* For Ubuntu's bundled LibreOffice, the icons of the individual LibreOffice document windows match the document categories.  (And "Help - About LibreOffice" reports the gtk3 VCL backend.)
* And also for the 6.4.4.2 Flatpak version, the icons of the individual LibreOffice document windows match the document categories.  (And "Help - About LibreOffice" reports the gtk3 VCL backend.)

**Comment by theworldisnotflat** [comment]
yet in my Ubuntu 18.04.4, with the 6.4.4.2 Flatpak version of Libreoffice I have the blank icons; I checked that `set | grep WAYLAND` gives no result and LO help has "VCL gtk3"
What's wrong then?

**Comment by stbergmann** [comment]
> yet in my Ubuntu 18.04.4, with the 6.4.4.2 Flatpak version of Libreoffice I have the blank icons; I checked that `set | grep WAYLAND` gives no result and LO help has "VCL gtk3"

Just to make sure:  The output of `flatpak run --command=bash org.libreoffice.LibreOffice -c set | grep WAYLAND` is also empty, I very much assume.

**Comment by theworldisnotflat** [comment]
yes I confirm `flatpak run --command=bash org.libreoffice.LibreOffice -c set | grep WAYLAND ` in terminal returns nothing
