### ISSUE TITLE
Missing window decoration (title bar) on KDE Plasma Wayland session

### ISSUE THREAD

**Issue by glaubersm** [flathub/org.libreoffice.LibreOffice#61]
My system:
Arch Linux 
libreoffice 6.1.3.2
flatpak 1.1.0
KDE Plasma Version: 5.14.3
Qt Version: 5.12.0 beta4
KDE Frameworks Version: 5.52.0

![lo](https://user-images.githubusercontent.com/15967631/48715426-20d64780-ebfc-11e8-88cf-338f15df97b9.png)

**Comment by TingPing** [comment]
Sounds like an upstream bug.

**Comment by laichiaheng** [comment]
It happens in Gnome 3, too.
#60

**Comment by stbergmann** [comment]
> Have you noticed that the icon of LibreOffice Writer is wrong?

Please keep each issue on a single topic.  (And yes, wrong icon is probably <https://github.com/flathub/org.libreoffice.LibreOffice/issues/60> "wrong icon on the dock".)

**Comment by Alexander-Wilms** [comment]
This issue is reproducible with the daily AppImage build, but can be worked around using `SAL_USE_VCLPLUGIN=qt5`. I assume one 6.2 has been released, this env var should be added to the Flatpak.

**Comment by stbergmann** [comment]
I can reproduce with a Fedora 29 Plasma (Wayland) desktop:  While the current flathub LO 6.1.4.2 lacks the title bar, a local flatpak build of upcoming LO 6.2 does have the title bar.  Likely either fixed by changes in LO itself, or in the underlying org.freedesktop.Platform runtime (which changes from 1.6 to 18.08 for LO 6.2, see <https://github.com/flathub/org.libreoffice.LibreOffice/issues/54> "Build against org.freedesktop.Platform 18.08").
So the hope is that this can be closed as "WORKSFORME" when flathub LO 6.2 is available.

**Comment by glaubersm** [comment]
Upgrade to LO 6.2.0.3 solved the problem on my system. \o/

**Comment by stbergmann** [comment]
Thanks for the confirmation.  So can close as "WORKSFORME" as expected.
