### ISSUE TITLE
LibreOffice 6.2 stuck on splash screen

### ISSUE THREAD

**Issue by wstoermer** [flathub/org.libreoffice.LibreOffice#72]
LibreOffice 6.2 will not start, and it hangs on the splash screen. It does not load, even after a long amount of time (20-30min). I like LibreOffice, and I want to use the new features in 6.2, but it will not load properly, and it will not run. 

I am running a fresh install of Fedora Workstation 29 (yes I installed the Flatpak repo), and it should work, but no. The older version works, but it does not have all of the cool new features.

I installed it through the GUI and the terminal, but they both had the same problem.

**Comment by stbergmann** [comment]
The splash screen stays on the screen?
Does its progress bar fill to any percentage?
Are you using GNOME or some other desktop?
X11 or Wayland?
Does running `flatpak run org.libreoffice.LibreOffice --safe-mode` from a command line work?

**Comment by wstoermer** [comment]
The splash screen stays on the screen? It does stay on the screen, and I
have waited 30 minutes and nothing happened each time.

Does its progress bar fill to any percentage? The bar sometimes fills and
the splash screen goes away, but most of the time the bar does not fill and
it just hangs there. In both scenarios I have waited 30 minutes, and
nothing happens.

Are you using GNOME or some other desktop? I am using the stock gnome
desktop that comes with Fedora 29, and I am only using the user themes
add-on.
X11 or Wayland? As far as I know, Wayland

Does running flatpak run org.libreoffice.LibreOffice --safe-mode from a
command line work?

I've done everything through graphical interface, and from the command line
oh, but it seems to yield the same results.

I wish I had better news, and thank you for taking up my case.

**Comment by stbergmann** [comment]
> > Does running `flatpak run org.libreoffice.LibreOffice --safe-mode` from a command line work?

> I've done everything through graphical interface, and from the command line oh, but it seems to yield the same results.

So, just to be sure, `flatpak run org.libreoffice.LibreOffice --safe-mode` displays the progress bar and then hangs, too?

(I'm on Fedora 29 GNOME Wayland, too, and for me everything works fine.  I start to run out of ideas as to what the problem could be for you.)

**Comment by wstoermer** [comment]
I reinstalled it, and it seems to open in safe mode, but I am not sure of
how I am to proceed.

**Comment by wstoermer** [comment]
Okay... I have no idea what I just did, but it seems to work now. All I did
was open in safe mode, reset the user profile, told it to continue in safe
mode, and selected the writer program, and then I closed it and opened it
from the terminal in normal mode

**Comment by stbergmann** [comment]
There must be something in your LibreOffice user profile (at `~/.var/app/org.libreoffice.LibreOffice/config/libreoffice/`, which keeps being reused across newly installed versions of LibreOffice) that caused that hang.  If you do not have any valuable configuration data for your LibreOffice Flatpak version (like what documents you recently opened, what "Tools - Options..." configurations you changed, what extensions you installed, etc.), then the easiest fix is to drop the existing user profile and let LibreOffice start with a fresh one.  Either, when the `--safe-mode` "Safe Mode" dialog is up, chose "Reset to factory settings: Reset entire user profile" and "Apply Changes and Restart".  (There appears to be a bug with Safe Mode, so that it restarts in Safe Mode again and shows the "Safe Mode" dialog again.  At which point, "Continue in Safe Mode" and quit LibreOffice and restart normally without `--safe-mode`; e.g., by clicking its icon or however you normally started LibreOffice in the past.)  Or, with no LibreOffice running, type `rm -fr ~/.var/app/org.libreoffice.LibreOffice/config/libreoffice` into a command line.

**Comment by stbergmann** [comment]
> Okay... I have no idea what I just did, but it seems to work now. All I did was open in safe mode, reset the user profile, told it to continue in safe mode, and selected the writer program, and then I closed it and opened it from the terminal in normal mode

Then lets close this issue.  Sorry for the inconvenience.

**Comment by wstoermer** [comment]
Thank you for your help. I could not have done it without you and you are
wisdom.
