### ISSUE TITLE
chart symbole is missing

### ISSUE THREAD

**Issue by achimfrase** [flathub/org.libreoffice.LibreOffice#74]
As you can see in the picture below the symbols (dots) for chart data points are missing. They are not choosable.

![libreoffice_flatpak](https://user-images.githubusercontent.com/45271246/52658213-cdbe1900-2efa-11e9-9816-a863ae12fb8e.png)

**Comment by stbergmann** [comment]
@achimfrase, please provide a detailed recipe how to reproduce the issue, and what exactly is not working as expected (neither of which is clear, to me at least, from the provided screenshot).  Also, what version of LibreOffice Flatpak is that, and do you happen to know whether the issue is the specific to the Flatpak version?

**Comment by achimfrase** [comment]
@stbergmann you are right, as it seems this is not a Flatpak bug. I installed the rpm from libreoffice website and this version has the same problem.

**Comment by stbergmann** [comment]
@achimfrase it would be very useful if you could file an upstream bug at <https://bugs.documentfoundation.org/enter_bug.cgi?format=guided>.

**Comment by achimfrase** [comment]
Okay, filled Bug upstream.
